In [6]:
import torch
import torchvision
import construct
import prep
import pandas as pd

In [2]:
image_dir = 'data/10x'
labels_file = 'data/me.csv'

DATA = prep.prep_data(pd.read_csv(labels_file), image_dir)

transforms = torchvision.transforms.Compose([
                            torchvision.transforms.ToPILImage(),
                            torchvision.transforms.RandomRotation((-180,180)),
                            torchvision.transforms.CenterCrop((325)),
                            torchvision.transforms.ToTensor()
                                      ])

/Users/Will/GradSchool/CHEME/Project/FmPM/fmpm/will/prep.py:92: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  identification[i] = False
/Users/Will/GradSchool/CHEME/Project/FmPM/fmpm/will/prep.py:90: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  identification[i] = True


In [3]:
#Declaring iterator. The thing that will loop through our dataset.

data = prep.tenX_dataset(DATA, 'data/10x', transform =transforms)
criterion = torch.nn.CrossEntropyLoss()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
test, train = torch.utils.data.random_split(data, [int(.2*len(data)), len(data)-int(.2*len(data))])
BATCH_SIZE = 32
epochs = 100

In [4]:
cnn = construct.train(epochs, BATCH_SIZE, train, criterion)

EPOCH: 0, acc: 0.578125, loss: 1.7218413092195988
tensor([[ 0.4279, -0.3352],
        [ 0.4031, -0.3118],
        [ 0.4189, -0.3264],
        [ 0.4155, -0.3168],
        [ 0.4995, -0.3915],
        [ 0.4058, -0.3068],
        [ 0.3879, -0.3031],
        [ 0.4097, -0.3073],
        [ 0.4013, -0.3015],
        [ 0.3899, -0.3039],
        [ 0.4150, -0.3214],
        [ 0.4276, -0.3309],
        [ 0.3913, -0.2915],
        [ 0.4102, -0.3198],
        [ 0.4098, -0.3201],
        [ 0.3979, -0.3085],
        [ 0.4794, -0.3802],
        [ 0.4773, -0.3765],
        [ 0.4081, -0.3195],
        [ 0.4584, -0.3523],
        [ 0.4266, -0.3316],
        [ 0.4238, -0.3300],
        [ 0.4853, -0.3844],
        [ 0.3681, -0.2938]], grad_fn=<AddmmBackward>)
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 

EPOCH: 30, acc: 0.8697916641831398, loss: 0.335642172023654
tensor([[ 0.9712, -0.8108],
        [ 1.2244, -1.1596],
        [ 1.3640, -1.2917],
        [ 1.1254, -1.0179],
        [ 1.0029, -0.7939],
        [ 0.9997, -0.7936],
        [ 1.1960, -1.0898],
        [ 1.1463, -1.0450],
        [ 1.3079, -1.2201],
        [ 1.3465, -1.3700],
        [ 1.1443, -1.0389],
        [ 1.0655, -0.9270],
        [ 1.2431, -1.1508],
        [ 1.3380, -1.2568],
        [ 1.2823, -1.1926],
        [ 0.9974, -0.7735],
        [ 1.0942, -0.9450],
        [ 1.0981, -0.9316],
        [ 1.0521, -0.9201],
        [ 1.0141, -0.9363],
        [ 1.3825, -1.3121],
        [-0.9138,  0.5857],
        [ 1.1821, -1.1276],
        [ 1.0204, -0.8264]], grad_fn=<AddmmBackward>)
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 0],
  

EPOCH: 60, acc: 0.8828125, loss: 0.30176665633916855
tensor([[ 0.9575, -0.7831],
        [ 0.1979,  0.0732],
        [ 1.9039, -1.6217],
        [ 1.3853, -0.9288],
        [ 2.0486, -1.8228],
        [ 2.0222, -1.7479],
        [ 0.0833,  0.2000],
        [ 1.0965, -0.6012],
        [ 1.8869, -1.5211],
        [ 0.2961, -0.0772],
        [-1.0323,  1.3826],
        [ 1.5589, -1.1621],
        [ 0.9830, -0.7461],
        [ 1.2117, -0.7411],
        [ 0.6369, -0.2408],
        [ 1.5469, -1.1897],
        [-2.0454,  2.4303],
        [ 1.3449, -0.9024],
        [-0.1837,  0.4753],
        [ 1.9822, -1.7624],
        [ 1.5101, -1.4254],
        [ 1.2558, -0.7580],
        [ 1.2759, -0.7676],
        [ 0.6521, -0.4641]], grad_fn=<AddmmBackward>)
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [

EPOCH: 89, acc: 0.87109375, loss: 0.3056029677391052
EPOCH: 90, acc: 0.9010416641831398, loss: 0.2714605648070574
tensor([[ 1.5906, -1.4947],
        [ 1.9953, -2.0341],
        [-0.0889,  0.1088],
        [ 1.0251, -0.7769],
        [-0.0783,  0.3388],
        [-2.4546,  2.5667],
        [ 1.8606, -1.8951],
        [ 1.0017, -0.6596],
        [-1.4149,  1.5766],
        [ 0.5213, -0.4713],
        [ 1.5544, -1.3973],
        [ 1.7944, -1.8279],
        [ 1.5628, -1.5458],
        [ 1.9447, -1.9280],
        [ 0.0394,  0.0192],
        [ 1.0381, -0.7782],
        [ 1.3239, -1.2706],
        [ 1.1882, -1.3257],
        [ 1.0503, -0.8146],
        [-1.0197,  1.0471],
        [-2.1301,  2.3339],
        [-0.1834,  0.1505],
        [ 1.6930, -1.7046],
        [-1.5909,  1.5865]], grad_fn=<AddmmBackward>)
tensor([[1, 0],
        [1, 0],
        [1, 0],
        [0, 1],
        [0, 1],
        [0, 1],
        [1, 0],
        [1, 0],
        [0, 1],
        [1, 0],
        [1, 0],
        [1, 

In [21]:
def get_predictions(batch_size, model, dataset, device=torch.device('cpu')):

    model.eval()
    images = []
    labels = []
    weights = []
    predictions = []
    
    iterator = torch.utils.data.DataLoader(dataset, 
                                 shuffle = False, 
                                 batch_size = batch_size)

    with torch.no_grad():
        for sample in iterator:
            image = sample['image'].to(device)
            isPlasticRaw = sample['plastic'].to(device)
            y_pred = model(image)
            
            images.append(image)
            labels.append(isPlasticRaw)
            weights.append(y_pred)
            predictions.append(y_pred.argmax(dim=1))

    images = torch.cat(images, dim=0)
    labels = torch.cat(labels, dim=0)
    weights = torch.cat(weights, dim=0)
    predictions = torch.cat(predictions, dim=0)
    acc = (labels[:,1] == predictions).float().sum()/len(predictions)
    return images, labels, predictions, weights, acc

In [25]:
images, labels, predictions, weights, acc = get_predictions(BATCH_SIZE, cnn, test, device)

In [28]:
predictions

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
(labels[:,1] == predictions).float().sum()/len(predictions)

tensor(0.8689)

In [45]:
(labels[:,1] == 0).float().sum()/len(predictions)

tensor(0.8361)

In [ ]:
def test_dataset_class():
    filename = '../tests/test_assets/test_labels_unclean.csv'
    image_dir = '../tests/test_assets/test_images'
    
    #Eventually just read in already cleaned labels sheet
    labels = prep_data(pd.read_csv(filename), image_dir)
    
    
    transform = None
    test_dataset = tenX_dataset(labels, image_dir, transform)
    
    #len() check
    length = len(test_dataset)
    expect = 5
    assert length is expect, f'10x dataset length method failed. Got {length}, should be {expect}'
    
    #get_item() check
    samples = []
    keys = ['image', 'plastic','shape','color']
    for i in range(len(test_dataset)):
        assert test_dataset[i]['image'] is not None, 'Got NoneType instead of image'
        isP = test_dataset[i]['plastic']
        assert math.isclose(0,isP) or math.isclose(1,isP), f'plastic not 0 or 1, instead is {isP}'
        length = len(test_dataset[i]['shape'])
        assert length is 4, f'length of shape array not 4, instead is {length}'
        samples.append(test_dataset[i])
        
    shape = samples[0]['shape']
    assert math.isclose(shape[2], 1),  f'wrong shape first image, is {shape}'
    color = samples[0]['color']
    assert math.isclose(color[0], 1), f'wrong color first image, is {color}'
    assert math.isclose(samples[4]['plastic'], 1), 'wrong plastic id 3rd image'
    
test_dataset_class()